#!/bin/bash
# docker/scripts/generate-compose.sh
# Generates docker-compose.yml from backups directory contents

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="${DOCKER_DIR}/docker-compose.yml"
BACKUPS_DIR="${DOCKER_DIR}/backups"
ENV_DIR="${DOCKER_DIR}/env"

# Default resource limits
DEFAULT_CPU_LIMIT="1.0"
DEFAULT_MEMORY_LIMIT="1536M"
DEFAULT_MEMORY_RESERVATION="512M"

log() {
    echo "[generate-compose] $*" >&2
}

# Find all bot backups
find_bots() {
    local bots=()
    if [[ -d "$BACKUPS_DIR" ]]; then
        for backup in "$BACKUPS_DIR"/*.zip "$BACKUPS_DIR"/*.tar.gz; do
            [[ -f "$backup" ]] || continue
            local botname=$(basename "$backup" | sed -E 's/\.(zip|tar\.gz)$//')
            bots+=("$botname")
        done
    fi
    printf '%s\n' "${bots[@]}" | sort -u
}

generate_service() {
    local bot="$1"
    local backup_file=""
    
    # Find backup file (prefer .zip)
    if [[ -f "${BACKUPS_DIR}/${bot}.zip" ]]; then
        backup_file="/backups/${bot}.zip"
    elif [[ -f "${BACKUPS_DIR}/${bot}.tar.gz" ]]; then
        backup_file="/backups/${bot}.tar.gz"
    else
        log "Warning: No backup found for ${bot}"
        backup_file=""
    fi

    # Check for env file
    local env_file_section=""
    if [[ -f "${ENV_DIR}/${bot}.env" ]]; then
        env_file_section="    env_file:
      - ./env/${bot}.env"
    fi

    # Check for backup volume mount
    local backup_volume=""
    if [[ -n "$backup_file" ]]; then
        backup_volume="      - ./backups/${bot}$(echo "$backup_file" | sed 's/.*\././'):${backup_file}:ro"
    fi

    cat << EOF
  ${bot}:
    image: openclaw-base:latest
    container_name: bot-${bot}
    hostname: ${bot}
    networks:
      - net-${bot}
    volumes:
      - data-${bot}:/data
${backup_volume}
    environment:
      - BOT_NAME=${bot}
      - GATEWAY_PORT=8080
${env_file_section}
    deploy:
      resources:
        limits:
          cpus: "${DEFAULT_CPU_LIMIT}"
          memory: ${DEFAULT_MEMORY_LIMIT}
        reservations:
          memory: ${DEFAULT_MEMORY_RESERVATION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

EOF
}

generate_network() {
    local bot="$1"
    cat << EOF
  net-${bot}:
    driver: bridge
    internal: false
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"

EOF
}

generate_volume() {
    local bot="$1"
    echo "  data-${bot}:"
    echo ""
}

main() {
    local bots
    mapfile -t bots < <(find_bots)

    if [[ ${#bots[@]} -eq 0 ]]; then
        log "No bot backups found in ${BACKUPS_DIR}"
        log "Add backup files (e.g., prof-costelinha.zip) to generate services"
        exit 1
    fi

    log "Found ${#bots[@]} bot(s): ${bots[*]}"
    log "Generating ${OUTPUT_FILE}..."

    # Generate header
    cat > "$OUTPUT_FILE" << 'EOF'
# docker-compose.yml
# Auto-generated by scripts/generate-compose.sh
# DO NOT EDIT MANUALLY - changes will be overwritten
#
# To regenerate: make docker-compose-gen
# To add a bot: place backup in docker/backups/<botname>.zip

version: "3.8"

services:
EOF

    # Generate services
    for bot in "${bots[@]}"; do
        generate_service "$bot" >> "$OUTPUT_FILE"
    done

    # Generate networks section
    echo "networks:" >> "$OUTPUT_FILE"
    for bot in "${bots[@]}"; do
        generate_network "$bot" >> "$OUTPUT_FILE"
    done

    # Generate volumes section
    echo "volumes:" >> "$OUTPUT_FILE"
    for bot in "${bots[@]}"; do
        generate_volume "$bot" >> "$OUTPUT_FILE"
    done

    log "Generated docker-compose.yml with ${#bots[@]} service(s)"
    log "Services: ${bots[*]}"
}

main "$@"
